// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: internal/proto/crawler.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_internal_proto_crawler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_crawler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_crawler_proto_rawDescGZIP(), []int{0}
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []byte                 `protobuf:"bytes,1,opt,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_internal_proto_crawler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_crawler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_crawler_proto_rawDescGZIP(), []int{1}
}

func (x *FetchResponse) GetProducts() []byte {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_internal_proto_crawler_proto protoreflect.FileDescriptor

const file_internal_proto_crawler_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/proto/crawler.proto\x12\x05proto\"\x0e\n" +
	"\fFetchRequest\"+\n" +
	"\rFetchResponse\x12\x1a\n" +
	"\bproducts\x18\x01 \x01(\fR\bproducts2L\n" +
	"\x0eCrawlerService\x12:\n" +
	"\rFetchProducts\x12\x13.proto.FetchRequest\x1a\x14.proto.FetchResponseB\x18Z\x16scraper/internal/protob\x06proto3"

var (
	file_internal_proto_crawler_proto_rawDescOnce sync.Once
	file_internal_proto_crawler_proto_rawDescData []byte
)

func file_internal_proto_crawler_proto_rawDescGZIP() []byte {
	file_internal_proto_crawler_proto_rawDescOnce.Do(func() {
		file_internal_proto_crawler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_crawler_proto_rawDesc), len(file_internal_proto_crawler_proto_rawDesc)))
	})
	return file_internal_proto_crawler_proto_rawDescData
}

var file_internal_proto_crawler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_crawler_proto_goTypes = []any{
	(*FetchRequest)(nil),  // 0: proto.FetchRequest
	(*FetchResponse)(nil), // 1: proto.FetchResponse
}
var file_internal_proto_crawler_proto_depIdxs = []int32{
	0, // 0: proto.CrawlerService.FetchProducts:input_type -> proto.FetchRequest
	1, // 1: proto.CrawlerService.FetchProducts:output_type -> proto.FetchResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_crawler_proto_init() }
func file_internal_proto_crawler_proto_init() {
	if File_internal_proto_crawler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_crawler_proto_rawDesc), len(file_internal_proto_crawler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_crawler_proto_goTypes,
		DependencyIndexes: file_internal_proto_crawler_proto_depIdxs,
		MessageInfos:      file_internal_proto_crawler_proto_msgTypes,
	}.Build()
	File_internal_proto_crawler_proto = out.File
	file_internal_proto_crawler_proto_goTypes = nil
	file_internal_proto_crawler_proto_depIdxs = nil
}
